name: 'Chromatic'

on:  
  push:
    branches:
      - main

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for the chromatic CLI to work

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Retrieve the cached main "node_modules" directory (if present)
        uses: actions/cache@v4
        id: node-cache-main
        with:
          path: node_modules
          key: node-modules-main-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      
      - name: Install main dependencies (if the cached directory was not found)
        if: steps.node-cache-main.outputs.cache-hit != 'true'
        run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          zip: true
          allowConsoleErrors: true
          